server:
  port: 8081
spring:
  application:
    name: korisnik
  config:
    import: optional:configserver:https://instruction-network-server-cfg.herokuapp.com
  cloud:
    config:
      uri: https://instruction-network-server-cfg.herokuapp.com