// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegistrationWithoutInputsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registrationWithoutInputs() {
    driver.get("http://localhost:3000/registration");
    driver.manage().window().setSize(new Dimension(1536, 824));
    driver.findElement(By.id("normal_login_firstname")).click();
    driver.findElement(By.cssSelector(".ant-input-affix-wrapper-focused")).click();
    driver.findElement(By.id("normal_login_email")).click();
    driver.findElement(By.cssSelector(".ant-input-affix-wrapper-focused")).click();
    driver.findElement(By.id("normal_login_password")).click();
    driver.findElement(By.cssSelector(".ant-btn > span")).click();
    driver.findElement(By.cssSelector(".ant-row:nth-child(2) .ant-form-item-explain > div")).click();
    driver.findElement(By.cssSelector(".ant-row:nth-child(2) .ant-form-item-explain > div")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ant-row:nth-child(2) .ant-form-item-explain > div"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".ant-row:nth-child(2) .ant-form-item-explain > div")).click();
    assertThat(driver.findElement(By.cssSelector(".ant-row:nth-child(2) .ant-form-item-explain > div")).getText(), is("Please input your first name!"));
    driver.findElement(By.cssSelector(".ant-row:nth-child(3) .ant-form-item-explain > div")).click();
    driver.findElement(By.cssSelector(".ant-row:nth-child(3) .ant-form-item-explain > div")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ant-row:nth-child(3) .ant-form-item-explain > div"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".ant-row:nth-child(3) .ant-form-item-explain > div")).click();
    assertThat(driver.findElement(By.cssSelector(".ant-row:nth-child(3) .ant-form-item-explain > div")).getText(), is("Please input your last name!"));
    driver.findElement(By.cssSelector(".ant-row:nth-child(4) .ant-form-item-explain > div")).click();
    driver.findElement(By.cssSelector(".ant-row:nth-child(4) .ant-form-item-explain > div")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ant-row:nth-child(4) .ant-form-item-explain > div"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".ant-row:nth-child(4) .ant-form-item-explain > div")).click();
    assertThat(driver.findElement(By.cssSelector(".ant-row:nth-child(4) .ant-form-item-explain > div")).getText(), is("Please input your e-mail!"));
    driver.findElement(By.cssSelector(".ant-row:nth-child(5) .ant-form-item-explain > div")).click();
    driver.findElement(By.cssSelector(".ant-row:nth-child(5) .ant-form-item-explain > div")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ant-row:nth-child(5) .ant-form-item-explain > div"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".ant-row:nth-child(5) .ant-form-item-explain > div")).click();
    assertThat(driver.findElement(By.cssSelector(".ant-row:nth-child(5) .ant-form-item-explain > div")).getText(), is("Please input your username!"));
    driver.findElement(By.cssSelector(".ant-row:nth-child(6) .ant-form-item-explain > div")).click();
    driver.findElement(By.cssSelector(".ant-row:nth-child(6) .ant-form-item-explain > div")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ant-row:nth-child(6) .ant-form-item-explain > div"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".ant-row:nth-child(6) .ant-form-item-explain > div")).click();
    driver.findElement(By.cssSelector(".ant-row:nth-child(6) .ant-form-item-explain > div")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ant-row:nth-child(6) .ant-form-item-explain > div"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".ant-row:nth-child(6) .ant-form-item-explain > div")).click();
    assertThat(driver.findElement(By.cssSelector(".ant-row:nth-child(6) .ant-form-item-explain > div")).getText(), is("Please input your password!"));
    driver.close();
  }
}
