// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegistrationElementsPresentTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registrationElementsPresent() {
    driver.get("http://localhost:3000/registration");
    driver.manage().window().setSize(new Dimension(1536, 824));
    {
      List<WebElement> elements = driver.findElements(By.id("normal_login_firstname"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("normal_login_lastname")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("normal_login_lastname"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".ant-input-affix-wrapper-focused")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".ant-input-affix-wrapper-focused"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("normal_login_username")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("normal_login_username"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".ant-input-password")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".ant-input-password"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.name("radiogroup"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".ant-radio-wrapper:nth-child(2) .ant-radio-input"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".ant-btn > span"));
      assert(elements.size() > 0);
    }
    driver.close();
  }
}
